version: '3.7'

services:
  curator:
    build:
      context: extensions/curator/
    init: true
    volumes:
      - ./extensions/curator/config/curator.yml:/usr/share/curator/config/curator.yml:ro,Z
      - ./extensions/curator/config/delete_log_files_curator.yml:/usr/share/curator/config/delete_log_files_curator.yml:ro,Z
    networks:
      - elk
    depends_on:
      - elasticsearch
