- hosts: webservers
  become: yes
  vars:
    http_port: 8000
    https_port: 4443
    html_welcome_msg: "Hello 90DaysOfDevOps - Welcome to Day 66!"
  tasks:
  - import_tasks: tasks/apache2_install.yml

  handlers:
  - import_tasks: handlers/main.yml